#!/bin/bash

echo "FILE NAME: $1"
echo

openocd  \
		       -f interface/stlink-v2-1.cfg \
		       -f target/stm32l4x.cfg \
		       -c "init" -c "reset halt" \
		       -c "flash write_image erase $1.srec" \
		       -c "reset" \
		       -c "shutdown" $NULL

