#!/bin/bash
# ccall <hub-server port>
# Program update a BMS string
# 09/15/2023
# 07/04/2024 - add ip and port as arguments
# Get a list of all parameter files

# Compile these two programs jic
cd ~/GliderWinchItems/BMS/PC/mklist1
gcc mklist1.c -o mklist1

echo "mklist1 compiled completed"

cd ~/GliderWinchItems/BMS/PC/mklist2
gcc mklist2.c -o mklist2

echo "mklist2 compiled completed"

# Make a list of CAN IDs that have parameter files
cd ~/GliderWinchItems/BMS/bmsadbms1818/params
ls *bq*.c > x;cat x | ../../PC/mklist1/mklist1

echo "mklist1 execution completed"

# Feed CAN msgs from hub-server->netcat to find
# CAN nodes that match the above list
# and generate a ./cc <CAN ID> file
# "../../bmsadbms1818/params/call_file"

 nc $1 $2 | ../../PC/mklist2/mklist2

echo "mklist2 execution complete"

# Make executable
chmod +x ../../bmsadbms1818/params/call_file

echo "call_file made executable"

echo "DONE"

# The following is commented out, remains jic is wanted
# Run the .cc file
# cd ~/GliderWinchItems/BMS/bmsadbms1818
# Example: call_file localhost 32123
# echo "call_file execute $1 $2"
# ./params/call_file $1 $2
