#!/bin/bash -e
# Load program over CAN
# ./cc <BMS ID> <hub-server> <port>
# E.g. ./cc B0A00000 localhost 32123

# Skip compiling. 02/17/26
#./mm $1

# Hack to do downloading out of @HOME
echo
echo "==== WARNING ===="
echo "SKIP COMPILE. LOAD PREVIOUSLY COMPILED CODE"
echo 
if [ -d $HOME/GliderWinchItems/tmp-xbin ]; then
	echo "directory exists: $HOME/GliderWinchItems/tmp-xbin"

else
	mkdir $HOME/GliderWinchItems/tmp-xbin
    echo "directory created: $HOME/GliderWinchItems/tmp-xbin"

fi

cp build/bms1818.xbin ~/G*ems/tmp-xbin

cd ~/GliderWinchCommons/embed/svn_discoveryf4/PC/sensor/CANldr/trunk
./CANldr $2 $3 $1 ~/GliderWinchItems/tmp-xbin/bms1818.xbin
echo $?
cd -

exit

